# AgentHub Auto-Generated Configuration
INSTANCE_NAME="{{NAME}}"
INSTANCE_SLUG="{{SLUG}}"
INSTANCE_TYPE="{{TYPE}}"
INSTANCE_PORT={{PORT}}
GATEWAY_URL="{{GATEWAY_URL}}"
HEALTH_CHECK_INTERVAL=30
LOG_LEVEL=info
